spring:
  application:
    name: mock-be
  datasource:
    url: ${MYSQL_URL:jdbc:mysql://192.168.3.102:10000/mock}
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:root123456}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      schema-locations: classpath:sql/schema.sql
      mode: always
      encoding: UTF-8
server:
  port: 8080
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true